### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by sairaamVenkatraman** [ethanleet/CapsNet#20]
I ran your code with default parameters and got a segmentation fault message.

**Comment by ethanleet** [comment]
Can you please provide more information about your environment (what version of Python, PyTorch, etc. are your running)? Also, did you simply run ``$ python train.py`` in command line and this error happens every time?

**Comment by sairaamVenkatraman** [comment]
To answer your second question first, yes, the error came after typing python train.py in the command line. Also, this error happens every time. I'm on python 3.6.4 and use pytorch 0.4.1, torchvision 0.2.1 and tqdm 4.25.0.
I've also found that the error happens when I try to use mnist. Also, it happens when I type python train.py -h

**Comment by ethanleet** [comment]
Thanks for the detail. I can't seem to reproduce your problem right now. Since this issue happens even when you run with `-h` flag, this might be a bug with `optparse` or some other libraries themselves. Does it actually print out the help message before getting a seg fault when you run with `-h`? What that flag does is that it should terminate the program as soon as the message is printed. If you can comment out the very last line in `train.py`, which is a function call to `main()`, it should still lead to a seg fault. Is that the case?

**Comment by sairaamVenkatraman** [comment]
Thank you for the quick reply. I did as you asked (commenting the last line) and still got a seg fault. Also, no help is printed when I run train.py with -h.

**Comment by ethanleet** [comment]
Yeah it seems that it might be an issue with some packages themselves in this case. Sorry I don't think there's anything I can do at the moment :(

**Comment by sairaamVenkatraman** [comment]
Thank you!
